apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python-pod
        image: python:3.11
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
spec:
  selector:
    app: python
